# Generated by Django 5.0.2 on 2024-02-29 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='start_date',
            field=models.CharField(max_length=50),
        ),
    ]
